version: '3.1'

services:
  user-cli:
    build: ./user-cli
    environment:
      MICRO_REGISTRY: "mdns"
    depends_on:
      - database

  user-service:
    build: ./user-service
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASS: "postgres"
      DB_NAME: "postgres"
    depends_on:
      - database

  email-service:
    build: ./email-service
    ports:
      - 50052:50051
    environment:
      MICRO_ADRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      EMAIL_HOST: "smtp.gmail.com"
      EMAIL_PORT: "587"
      EMAIL_USER: "johynpapin.priv@gmail.com"
      EMAIL_PASS: "SErplentin22"

  api-gateway:
      image: microhq/micro
      command: api --handler=rpc --address=:8080 --namespace=yonjuuni
      ports:
        - 8080:8080
      environment:
        MICRO_REGISTRY: "mdns"
      depends_on:
      - user-service

  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "postgres"