// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/email/email.proto

/*
Package jp_yonjuuni_srv_email is a generated protocol buffer package.

It is generated from these files:
	proto/email/email.proto

It has these top-level messages:
*/
package jp_yonjuuni_srv_email

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for EmailService service

type EmailServiceClient interface {
}

type emailServiceClient struct {
	c           client.Client
	serviceName string
}

func NewEmailServiceClient(serviceName string, c client.Client) EmailServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "jp.yonjuuni.srv.email"
	}
	return &emailServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

// Server API for EmailService service

type EmailServiceHandler interface {
}

func RegisterEmailServiceHandler(s server.Server, hdlr EmailServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&EmailService{hdlr}, opts...))
}

type EmailService struct {
	EmailServiceHandler
}

func init() { proto.RegisterFile("proto/email/email.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 80 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xcd, 0x4d, 0xcc, 0xcc, 0x81, 0x90, 0x7a, 0x60, 0x11, 0x21, 0xd1, 0xac, 0x02,
	0xbd, 0xca, 0xfc, 0xbc, 0xac, 0xd2, 0xd2, 0xbc, 0x4c, 0xbd, 0xe2, 0xa2, 0x32, 0x3d, 0xb0, 0xa4,
	0x11, 0x1f, 0x17, 0x8f, 0x2b, 0x88, 0x11, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x9a, 0xc4, 0x06,
	0x56, 0x6d, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x75, 0x58, 0xf4, 0x7b, 0x48, 0x00, 0x00, 0x00,
}
